### ISSUE TITLE
What is the license ?

### ISSUE THREAD

**Issue by ayourtch** [tehnerd/bgp2go#1]
Hey Nikita, interesting project - but can't find what kind of license is it under ? (Keeping the fingers crossed for something like MIT, but in any case clarifying that would be cool ! :-) Thanks a lot!

**Comment by tehnerd** [comment]
Hi, Andrew. Just added license file. it's a BSD's one. jfyi: i'm using this project mostly for playing around w/ bgp (there are a lot of unsafe things going on inside parsers; not always check len etc; there is at least 1 race in simple_injector etc). If you need production ready bgp in go - better look at https://github.com/osrg/gobgp this is bgp's implementation from guys, who works at NTT. and it's pretty stable/good

**Comment by ayourtch** [comment]
Hi Nikita! Super, thanks a lot! I intended to use this in a similar fashion - mostly to toy around with various ideas, since it seems a bit more compact compared with gobgp - but, thanks a lot for the warnings anyway! :-)
